FROM mcr.microsoft.com/devcontainers/rust:latest


RUN apt-get update && \
  apt-get install -y \
    libxcursor1 \
    libxcursor-dev \
    libxkbcommon-x11-0 \
    libxkbcommon-dev \
    x11-apps \
    libgl1 \
    libglx-mesa0 \
    mesa-utils
